
#
# Django
#
services:
  agro_test:
    container_name: agro_test
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./agro_test:/usr/src/app/agro_test
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: always

#
# Postgres
#
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
